GET http://localhost:8080/v1/restaurants?limit=4
###
POST http://localhost:8080/v1/restaurants
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXJfaWQiOjUsInJvbGUiOiJ1c2VyIn0sImV4cCI6MTY3NTI0MjgzMiwiaWF0IjoxNjcyNjUwODMyfQ.VDm2GEhC65hxY80Z-36KM90aqvaepLBEOLTW7cHg1yc
Content-Type: application/json

{
    "name": "Love ",
    "address": "H",
    "logo":  {
        "url": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fvietnamnet.vn%2Favatar-2-can-moc-nua-ty-do-sau-vai-ngay-rieng-viet-nam-thu-99-ty-dong-2092829.html&psig=AOvVaw2bGgRuw9EILtpUbeXfSMSZ&ust=1672067229655000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCICz4fuFlfwCFQAAAAAdAAAAABAE",
        "height" : 555,
        "width" : 921

    },
    "cover": [
        {
            "url": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fvietnamnet.vn%2Favatar-2-can-moc-nua-ty-do-sau-vai-ngay-rieng-viet-nam-thu-99-ty-dong-2092829.html&psig=AOvVaw2bGgRuw9EILtpUbeXfSMSZ&ust=1672067229655000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCICz4fuFlfwCFQAAAAAdAAAAABAE",
            "height" : 555,
            "width" : 921

        }
    ]
}
###
PATCH http://localhost:8080/v1/restaurants/1
Content-Type: application/json

{
    "name": "Tem1"
}

###
DELETE  http://localhost:8080/v1/restaurants/4

###
GET http://localhost:8080/restaurants/v1/iUwqQA5kiz98

###
POST  http://localhost:8080/v1/register
Content-Type: application/json

{
    "email": "200l@gmail.com",
    "password": "123456",
    "first_name": "Nhajat",
    "last_name": "Nhajat"
}


###
POST  http://localhost:8080/v1/login
Content-Type: application/json

{
    "email": "200l@gmail.com",
    "password": "123456"
}

### 
GET http://localhost:8080/v1/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXJfaWQiOjUsInJvbGUiOiJ1c2VyIn0sImV4cCI6MTY3NTQ5NzYyOCwiaWF0IjoxNjcyOTA1NjI4fQ.5phyzYyo__a8ze37L87H7WtS71VW-CA0Eag3BCY2-Tk


###
GET http://localhost:8080/v1/restaurants/gGzTBURqhajG/liked-users?limit=1

###
GET http://localhost:8080/v1/restaurants/3mKb6MT4gWZxRU/liked-restaurant?limit=1


###
POST  http://localhost:8080/v1/restaurants/3mMo3hVGTE4VTN/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXJfaWQiOjUsInJvbGUiOiJ1c2VyIn0sImV4cCI6MTY3NTQ5NzYyOCwiaWF0IjoxNjcyOTA1NjI4fQ.5phyzYyo__a8ze37L87H7WtS71VW-CA0Eag3BCY2-Tk



###
DELETE   http://localhost:8080/v1/restaurants/3mMo3hVGTE4VTN/unlike
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXJfaWQiOjUsInJvbGUiOiJ1c2VyIn0sImV4cCI6MTY3NTQ5NzYyOCwiaWF0IjoxNjcyOTA1NjI4fQ.5phyzYyo__a8ze37L87H7WtS71VW-CA0Eag3BCY2-Tk